server:
  port: 8081
  servlet:
    context-path: /luckymoney

#minMoney: 2
#description: 最少要发1
#description: 最少要发${minMoney}元


#给配置参数加一个前缀
limit: 
  minMoney: 2
  maxMoney: 888
  description: 最少要发${limit.minMoney}元，最大只能发${limit.maxMoney}元
  
  
#MySql数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.92.119.144:3306/jkchenDB?useUnicode=true&characterEncoding=utf8 #jkchenDB是数据库名
    username: jkchen
    password: 123456
  jpa:
    hibernate:
#      ddl-auto: create   #每次启动 时都会自动执行create表操作，如果存在表，则会先删除再新建表
      ddl-auto: update
    show-sql: true  #控制台显示sql语句